version: '3'
services:
  linkapi:
    build: './linkapi'
    ports:
      - "3002:3000"
    depends_on: 
      - db
    environment:
      - PORT=3000
      - DB_HOST=mongodb://linkapi/orders
      - BLING_API_KEY=e4bbb1db79e034b79843f61adebd713aa43144ca9abf79bdcb3638356e2f65303f5f8d32
      - BLING_BASE_URL=https://bling.com.br/Api/v2
      - PIPEDRIVE_BASE_URL=https://testlinkapi-sandbox.pipedrive.com
      - PIPEDRIVE_API_KEY=f183c575716e0329a5ba5aa75afbaf23077fc337
      - PIPEDRIVE_PAGINATION_LIMIT=5
      - PIPEDRIVE_CUSTOM_FILTER_ID=24

  db:
    image: mongo
    ports:
      - "27017:27017"